### ISSUE TITLE
component architecture plan

### ISSUE THREAD

**Issue by BriBourassa** [BriBourassa/Rancid-Tomatillos#16]
What components do you envision needing?
Where will data be stored?
How will information be passed around?

**Comment by BriBourassa** [comment]
Possible components: 

- App 
- Collection
- Movie 
- Modal (with movie info)

**Comment by chrissycooper** [comment]
Data will be stored in the App component and passed into the Collection which will map the data and return movie components.  The Modal component will be conditionally rendered when the Movie component is clicked on. I wonder if the Modal component will need a state, something like isOpen: t/f, so we can toggle it based on the click.
