### ISSUE TITLE
As a user, when I visit the app, all movies should be displayed

### ISSUE THREAD

**Issue by BriBourassa** [BriBourassa/Rancid-Tomatillos#4]

**Comment by chrissycooper** [comment]
The movies will be arranged in a grid. The user will have the option to hover over a movie to see it's average rating before clicking to find more information (this will be achieved later). This step involves utilizing the example data to display the images of the movies, adding some basic styling, and conditionally rendering a div with the rating on it. The div will be a transparent overlay which has the rating in plain and fairly large text. 

please reference the [letterboxd entry of the design inspo doc](https://docs.google.com/document/d/1srIRh5MrJXBae30LJY41n8-PJiu-fonFBZ5o2wIg1Q4/edit?usp=sharing) and the first screenshot below to see the hover state.

**Comment by chrissycooper** [comment]
![Image](https://user-images.githubusercontent.com/31836822/227534209-f53238a3-5f57-4b21-9d7e-5c4bdda1f1ba.png)

**Comment by chrissycooper** [comment]
![Image](https://user-images.githubusercontent.com/31836822/227537586-a1e293c9-94d9-425c-b861-5464ac7b3f33.png)
