### ISSUE TITLE
As a user, I can click a movie, and see that movie’s details

### ISSUE THREAD

**Issue by BriBourassa** [BriBourassa/Rancid-Tomatillos#6]

**Comment by chrissycooper** [comment]
The user should be able to click anywhere on a movie card and a modal window should pop up with the additional information we have about the movie. We took inspiration from netflix's modal window for the general shape and structure. So we are looking for a big image on top (maybe taking up about 3/4 of the space, no padding or border) with the title in a large font on top and a 1/4 area at the bottom with details like release date, and average rating again. There should be plenty of space in case there is extra information when the API is involved. I wonder if the backdrop image would be best here.

**Comment by chrissycooper** [comment]
![Image](https://user-images.githubusercontent.com/31836822/227535640-76b77fa6-2118-4c14-838f-2e0eb4ef38e8.png)

**Comment by chrissycooper** [comment]
See the [design inspo doc](https://docs.google.com/document/d/1srIRh5MrJXBae30LJY41n8-PJiu-fonFBZ5o2wIg1Q4/edit) to reference the netflix modal
